Repository knative-extensions/net-contour, pull requests merged in 2020-03, with the labels that each got.

#47 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, lgtm, size/S

#45 Format markdown
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#49 Auto-update dependencies
  Gopkg.lock
  config/contour/external.yaml
  config/contour/internal.yaml
Labels: approved, lgtm, size/L

#50 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/serving/pkg/activator/handler/concurrency_reporter.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/autoscaler.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/hpa/controller.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/controller.go
  vendor/knative.dev/serving/pkg/reconciler/certificate/controller.go
  vendor/knative.dev/serving/pkg/reconciler/configuration/controller.go
  vendor/knative.dev/serving/pkg/reconciler/gc/controller.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/controller.go
  vendor/knative.dev/serving/pkg/reconciler/labeler/controller.go
  vendor/knative.dev/serving/pkg/reconciler/logger.go
  vendor/knative.dev/serving/pkg/reconciler/metric/controller.go
  vendor/knative.dev/serving/pkg/reconciler/nscert/controller.go
  vendor/knative.dev/serving/pkg/reconciler/revision/controller.go
  vendor/knative.dev/serving/pkg/reconciler/route/controller.go
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/controller.go
  vendor/knative.dev/serving/pkg/reconciler/service/controller.go
  vendor/knative.dev/serving/test/config/autotls/certmanager/http01/mesh-issuer.yaml
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-basic-entrypoint.sh
  vendor/knative.dev/serving/test/v1/service.go
  vendor/knative.dev/serving/test/v1alpha1/service.go
  vendor/knative.dev/serving/test/v1beta1/service.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
Labels: approved, lgtm, size/L

#51 Cleanup a handful of unused fields.
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/controller.go
Labels: approved, lgtm, size/S

#55 Update dependencies
  Gopkg.lock
  config/contour/external.yaml
  config/contour/internal.yaml
  pkg/reconciler/contour/contour_test.go
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/name/ref.go
  vendor/github.com/google/go-containerregistry/pkg/name/repository.go
  vendor/github.com/google/go-containerregistry/pkg/name/tag.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.toml
  vendor/knative.dev/serving/OWNERS_ALIASES
  vendor/knative.dev/serving/config/200-clusterrole-ns-wildcard-certs.yaml
  vendor/knative.dev/serving/config/core/configmaps/autoscaler.yaml
  vendor/knative.dev/serving/config/namespace-wildcard-certs/200-clusterrole.yaml
  vendor/knative.dev/serving/docs/scaling/README.md
  vendor/knative.dev/serving/hack/update-deps.sh
  vendor/knative.dev/serving/pkg/activator/net/helpers.go
  vendor/knative.dev/serving/pkg/activator/net/throttler.go
  vendor/knative.dev/serving/pkg/autoscaler/metrics/metrics_provider.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/stub/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/certificate/stub/controller.go
  vendor/knative.dev/serving/pkg/metrics/key.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/pkg/queue/timeout.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/resources/metric.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/resources/sks.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/virtual_service.go
  vendor/knative.dev/serving/pkg/reconciler/revision/cruds.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/deploy.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/imagecache.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/meta.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/pa.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/certificate.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/ingress.go
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/resources/services.go
  vendor/knative.dev/serving/pkg/reconciler/service/resources/configuration.go
  vendor/knative.dev/serving/pkg/reconciler/service/resources/route.go
  vendor/knative.dev/serving/pkg/resources/meta.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/service.go
  vendor/knative.dev/serving/pkg/testing/v1beta1/service.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/prober.go
  vendor/knative.dev/serving/third_party/VENDOR-LICENSE
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
Labels: approved, lgtm, size/XXL

#57 Use ko's strict mode for better errors messages
  config/contour/external.yaml
  config/contour/internal.yaml
  config/controller.yaml
  hack/release.sh
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/S

#59 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/docs/scaling/DEVELOPMENT.md
  vendor/knative.dev/serving/docs/scaling/SYSTEM.md
  vendor/knative.dev/serving/docs/scaling/images/scale-from-0.png
  vendor/knative.dev/serving/docs/scaling/images/scale-to-0.png
  vendor/knative.dev/serving/docs/scaling/images/scale-up-down.png
  vendor/knative.dev/serving/pkg/reconciler/labeler/controller.go
  vendor/knative.dev/serving/pkg/reconciler/labeler/labels.go
  vendor/knative.dev/serving/test/apicoverage/image/apicoverage-webhook.yaml
  vendor/knative.dev/serving/test/performance/benchmarks/dataplane-probe/continuous/dataplane-probe-setup.yaml
  vendor/knative.dev/serving/test/performance/benchmarks/dataplane-probe/continuous/dataplane-probe.yaml
  vendor/knative.dev/serving/test/performance/benchmarks/deployment-probe/continuous/benchmark.yaml
  vendor/knative.dev/serving/test/performance/benchmarks/load-test/continuous/load-test-setup.yaml
  vendor/knative.dev/serving/test/performance/benchmarks/load-test/continuous/load-test.yaml
  vendor/knative.dev/serving/test/performance/benchmarks/scale-from-zero/continuous/scale-from-zero.yaml
  vendor/knative.dev/serving/test/performance/config/job.yaml
  vendor/knative.dev/serving/test/test_images/autoscale/service.yaml
  vendor/knative.dev/serving/test/test_images/failing/service.yaml
  vendor/knative.dev/serving/test/test_images/flaky/service.yaml
  vendor/knative.dev/serving/test/test_images/grpc-ping/service.yaml
  vendor/knative.dev/serving/test/test_images/hellovolume/service.yaml
  vendor/knative.dev/serving/test/test_images/helloworld/helloworld.yaml
  vendor/knative.dev/serving/test/test_images/helloworld/service.yaml
  vendor/knative.dev/serving/test/test_images/httpproxy/service.yaml
  vendor/knative.dev/serving/test/test_images/observed-concurrency/service.yaml
  vendor/knative.dev/serving/test/test_images/pizzaplanetv1/service.yaml
  vendor/knative.dev/serving/test/test_images/pizzaplanetv2/service.yaml
  vendor/knative.dev/serving/test/test_images/runtime/service.yaml
  vendor/knative.dev/serving/test/test_images/singlethreaded/service.yaml
  vendor/knative.dev/serving/test/test_images/timeout/service.yaml
  vendor/knative.dev/serving/test/test_images/wsserver-hostname/service.yaml
  vendor/knative.dev/serving/test/test_images/wsserver/service.yaml
  vendor/knative.dev/serving/test/v1alpha1/configuration.go
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/XL

#60 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/hpa/hpa.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/kpa.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/reconciler.go
  vendor/knative.dev/serving/test/prober.go
  vendor/knative.dev/serving/third_party/kourier-latest/download-kourier.sh
  vendor/knative.dev/serving/third_party/kourier-latest/kourier.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#62 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/OWNERS_ALIASES
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/third_party/istio-1.4-latest
  vendor/knative.dev/serving/third_party/istio-1.4.6/README.md
  vendor/knative.dev/serving/third_party/istio-1.4.6/download-istio.sh
  vendor/knative.dev/serving/third_party/istio-1.4.6/drain-seconds.yaml.patch
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-ci-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-ci-no-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-crds.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-knative-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-minimal.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/namespace.yaml.patch
  vendor/knative.dev/serving/third_party/istio-1.4.6/values-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/values-lean.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/values-local.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/values.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#63 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/factory.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/cmd/activator/main.go
  vendor/knative.dev/serving/config/core/resources/configuration.yaml
  vendor/knative.dev/serving/config/core/resources/revision.yaml
  vendor/knative.dev/serving/config/core/resources/route.yaml
  vendor/knative.dev/serving/config/core/resources/service.yaml
  vendor/knative.dev/serving/pkg/activator/net/throttler.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/performance/performance-tests.sh
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/istio-1.5-latest
  vendor/knative.dev/serving/third_party/istio-1.5.0/README.md
  vendor/knative.dev/serving/third_party/istio-1.5.0/download-istio.sh
  vendor/knative.dev/serving/third_party/istio-1.5.0/drain-seconds.yaml.patch
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-ci-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-ci-no-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-crds.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-knative-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-minimal.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/namespace.yaml.patch
  vendor/knative.dev/serving/third_party/istio-1.5.0/values-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/values-lean.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/values-local.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/values.yaml
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XXL

#64 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/prow/env.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/OWNERS_ALIASES
  vendor/knative.dev/serving/config/core/configmaps/defaults.yaml
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/pkg/reconciler/labeler/labels.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/configuration.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#65 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.toml
  vendor/knative.dev/serving/README.md
  vendor/knative.dev/serving/cmd/activator/main.go
  vendor/knative.dev/serving/pkg/activator/net/helpers.go
  vendor/knative.dev/serving/pkg/activator/net/throttler.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/performance/performance-tests.sh
  vendor/knative.dev/serving/third_party/VENDOR-LICENSE
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#66 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/config/core/configmaps/autoscaler.yaml
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/M

#69 Fix NPE when defaulting webhook isn't present
  pkg/reconciler/contour/resources/httpproxy.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#72 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  vendor/knative.dev/serving/pkg/autoscaler/metrics/sample_size.go
  vendor/knative.dev/serving/pkg/autoscaler/metrics/stats_scraper.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#74 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/M

#75 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.toml
  vendor/knative.dev/serving/pkg/autoscaler/scaling/multiscaler.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/resources/decider.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e/autotls/config/dnssetup/main.go
  vendor/knative.dev/serving/test/e2e/autotls/config/util.go
  vendor/knative.dev/serving/third_party/VENDOR-LICENSE
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#76 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/pkg/activator/net/throttler.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/autoscaler.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/multiscaler.go
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/knative.dev/serving/test/config/autotls/certmanager/caissuer/config-certmanager.yaml
  vendor/knative.dev/serving/test/config/autotls/certmanager/caissuer/generate.sh
  vendor/knative.dev/serving/test/config/autotls/certmanager/caissuer/issuer.yaml
  vendor/knative.dev/serving/test/config/autotls/certmanager/caissuer/secret.yaml
  vendor/knative.dev/serving/test/conformance/api/v1/blue_green_test.go
  vendor/knative.dev/serving/test/conformance/api/v1/generatename_test.go
  vendor/knative.dev/serving/test/conformance/api/v1/resources_test.go
  vendor/knative.dev/serving/test/conformance/api/v1/revision_timeout_test.go
  vendor/knative.dev/serving/test/conformance/api/v1/route_test.go
  vendor/knative.dev/serving/test/conformance/api/v1/service_test.go
  vendor/knative.dev/serving/test/conformance/api/v1/single_threaded_test.go
  vendor/knative.dev/serving/test/conformance/api/v1/util.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/blue_green_test.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/generatename_test.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/resources_test.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/revision_timeout_test.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/route_test.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/service_test.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/single_threaded_test.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/util.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/volumes_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/blue_green_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/generatename_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/resources_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/revision_timeout_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/route_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/service_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/single_threaded_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/util.go
  vendor/knative.dev/serving/test/conformance/runtime/readiness_probe_test.go
  vendor/knative.dev/serving/test/conformance/runtime/util.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/serving/test/performance/benchmarks/scale-from-zero/continuous/main.go
  vendor/knative.dev/serving/test/performance/latency_test.go
  vendor/knative.dev/serving/test/performance/observed_concurency_test.go
  vendor/knative.dev/serving/test/upgrade/probe_test.go
  vendor/knative.dev/serving/test/util.go
  vendor/knative.dev/serving/test/v1alpha1/service.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/XL

#77 Fix presubmit-tests.sh argument passing.
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#78 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/kvstore/kvstore.go
  vendor/knative.dev/pkg/kvstore/kvstore_cm.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/pkg/reconciler/testing/v1alpha1/factory.go
  vendor/knative.dev/serving/pkg/reconciler/testing/v1alpha1/listers.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/ha/autoscalerhpa_test.go
  vendor/knative.dev/serving/test/ha/controller_test.go
  vendor/knative.dev/serving/test/ha/ha.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XL

#81 Track the Contour release branch.
  Gopkg.lock
  Gopkg.toml
  hack/update-deps.sh
  vendor/github.com/projectcontour/contour/examples/contour/03-contour.yaml
  vendor/github.com/projectcontour/contour/examples/contour/03-envoy.yaml
  vendor/github.com/projectcontour/contour/examples/render/contour.yaml
  vendor/github.com/projectcontour/contour/site/_redirects
Labels: approved, cla: yes, lgtm, size/M

#82 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/serving/config/core/configmaps/logging.yaml
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/test/config/config-logging.yaml
  vendor/knative.dev/serving/test/conformance/api/v1/single_threaded_test.go
  vendor/knative.dev/serving/test/conformance/api/v1alpha1/single_threaded_test.go
  vendor/knative.dev/serving/test/conformance/api/v1beta1/single_threaded_test.go
  vendor/knative.dev/serving/test/conformance/certificate/nonhttp01/certificate_test.go
  vendor/knative.dev/serving/test/conformance/certificate/utils.go
Labels: approved, cla: yes, lgtm, size/M

#84 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.toml
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/serving/test/conformance/ingress/visibility_test.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/XL

#85 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/autoscaler.go
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/hpa/hpa.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/kpa.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/reconciler.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/resources/sks.go
  vendor/knative.dev/serving/pkg/reconciler/route/route.go
  vendor/knative.dev/serving/pkg/testing/functional.go
  vendor/knative.dev/serving/pkg/testing/v1/configuration.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/clients.go
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/serving/test/v1/configuration.go
  vendor/knative.dev/serving/test/v1/route.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L
