Repository knative-extensions/net-contour, pull requests merged in 2020-06, with the labels that each got.

#132 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#133 Consume the exposed ingress conformance test as a library
  go.mod
  go.sum
  hack/update-deps.sh
  test/conformance/ingress/README.md
  test/conformance/ingress/util.go
  test/conformance/ingress_test.go
  test/e2e-tests.sh
  vendor/github.com/mikefarah/yq/v3/README.md
  vendor/knative.dev/serving/config/core/configmaps/defaults.yaml
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/test/conformance/ingress/basic.go
  vendor/knative.dev/serving/test/conformance/ingress/grpc.go
  vendor/knative.dev/serving/test/conformance/ingress/headers.go
  vendor/knative.dev/serving/test/conformance/ingress/hosts.go
  vendor/knative.dev/serving/test/conformance/ingress/path.go
  vendor/knative.dev/serving/test/conformance/ingress/percentage.go
  vendor/knative.dev/serving/test/conformance/ingress/retry.go
  vendor/knative.dev/serving/test/conformance/ingress/run.go
  vendor/knative.dev/serving/test/conformance/ingress/timeout.go
  vendor/knative.dev/serving/test/conformance/ingress/tls.go
  vendor/knative.dev/serving/test/conformance/ingress/update.go
  vendor/knative.dev/serving/test/conformance/ingress/visibility.go
  vendor/knative.dev/serving/test/conformance/ingress/websocket.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#136 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#137 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/serving/config/core/configmaps/autoscaler.yaml
  vendor/knative.dev/serving/config/core/configmaps/defaults.yaml
  vendor/knative.dev/serving/config/core/configmaps/deployment.yaml
  vendor/knative.dev/serving/config/core/configmaps/domain.yaml
  vendor/knative.dev/serving/config/core/configmaps/features.yaml
  vendor/knative.dev/serving/config/core/configmaps/gc.yaml
  vendor/knative.dev/serving/config/core/configmaps/leader-election.yaml
  vendor/knative.dev/serving/config/core/configmaps/logging.yaml
  vendor/knative.dev/serving/config/core/configmaps/network.yaml
  vendor/knative.dev/serving/config/core/configmaps/observability.yaml
  vendor/knative.dev/serving/config/core/configmaps/tracing.yaml
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/service_lifecycle.go
  vendor/knative.dev/serving/test/conformance/ingress/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#138 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_lifecycle.go
  vendor/knative.dev/serving/test/v1alpha1/ingress.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#140 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/serving/config/core/configmaps/autoscaler.yaml
  vendor/knative.dev/serving/config/core/configmaps/defaults.yaml
  vendor/knative.dev/serving/config/core/configmaps/deployment.yaml
  vendor/knative.dev/serving/config/core/configmaps/domain.yaml
  vendor/knative.dev/serving/config/core/configmaps/features.yaml
  vendor/knative.dev/serving/config/core/configmaps/gc.yaml
  vendor/knative.dev/serving/config/core/configmaps/leader-election.yaml
  vendor/knative.dev/serving/config/core/configmaps/logging.yaml
  vendor/knative.dev/serving/config/core/configmaps/network.yaml
  vendor/knative.dev/serving/config/core/configmaps/observability.yaml
  vendor/knative.dev/serving/config/core/configmaps/tracing.yaml
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_lifecycle.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#142 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#143 Remove unused const
  pkg/reconciler/contour/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#135 Run `yq` dependency from vendor rather than `go get` and `go install`
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/S

#144 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/serving/config/core/configmaps/autoscaler.yaml
  vendor/knative.dev/serving/config/core/configmaps/deployment.yaml
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/route.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/service.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
Labels: approved, cla: yes, lgtm, size/XXL

#145 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/serving/config/core/configmaps/features.yaml
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/test/test_images/runtime/handlers/handler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#146 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/serving/config/core/configmaps/autoscaler.yaml
  vendor/knative.dev/serving/config/core/configmaps/defaults.yaml
  vendor/knative.dev/serving/config/core/configmaps/deployment.yaml
  vendor/knative.dev/serving/config/core/configmaps/domain.yaml
  vendor/knative.dev/serving/config/core/configmaps/features.yaml
  vendor/knative.dev/serving/config/core/configmaps/gc.yaml
  vendor/knative.dev/serving/config/core/configmaps/leader-election.yaml
  vendor/knative.dev/serving/config/core/configmaps/logging.yaml
  vendor/knative.dev/serving/config/core/configmaps/network.yaml
  vendor/knative.dev/serving/config/core/configmaps/observability.yaml
  vendor/knative.dev/serving/config/core/configmaps/tracing.yaml
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#148 Add support for header conditions
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, cla: yes, lgtm, size/M
