Repository knative-extensions/net-contour, pull requests merged in 2020-07, with the labels that each got.

#147 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/config/core/configmaps/leader-election.yaml
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#152 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/serving/config/core/configmaps/leader-election.yaml
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/v1alpha1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#153 Pin to knative.dev/serving@release-16
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#158 Enable chaos testing on net-contour
  hack/tools.go
  test/config/chaosduck.yaml
  test/e2e-common.sh
  vendor/knative.dev/pkg/kflag/doc.go
  vendor/knative.dev/pkg/kflag/set.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#160 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.mod
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/test/logging/logger_writer.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/serving/config/core/configmaps/features.yaml
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#161 Interpret "no timeout" as infinite.
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, cla: yes, lgtm, size/S

#163 Filter on the OwnerRef GroupKind.
  pkg/reconciler/contour/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#162 Pull in class-based genreconciler
  go.mod
  go.sum
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/controller.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/knative.dev/networking/pkg/apis/config/defaults.go
  vendor/knative.dev/networking/pkg/apis/config/doc.go
  vendor/knative.dev/networking/pkg/apis/config/store.go
  vendor/knative.dev/networking/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/test/logging/logger_writer.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/knative.dev/serving/test/conformance/ingress/run.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#166 Add a scheme for warming Endpoints before rolling our kingress changes.
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/controller.go
  pkg/reconciler/contour/resources/constants.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  pkg/reconciler/contour/resources/kingress.go
  pkg/reconciler/contour/resources/kingress_test.go
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#164 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/test_images/runtime/handlers/handler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#170 Disable test-update until it is really fixed.
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#169 Enable debugging logging during e2e tests
  test/config/config-logging.yaml
Labels: approved, cla: yes, lgtm, size/S

#167 Clean up the endpoint probe kingress after the parent is ready.
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
Labels: approved, cla: yes, lgtm, size/M

#168 Drop the endpoints checks.
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/controller.go
Labels: approved, cla: yes, lgtm, size/L

#172 Guard the DeleteCollection in a Lister lookup.
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
Labels: approved, cla: yes, lgtm, size/M

#173 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#177 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/proxy.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/helper.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/serving/config/core/configmaps/features.yaml
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_validation.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/configuration.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/revision.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/service.go
  vendor/knative.dev/serving/test/conformance/ingress/rewrite.go
  vendor/knative.dev/serving/test/conformance/ingress/run.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL
