Repository knative-extensions/net-contour, pull requests merged in 2020-09, with the labels that each got.

#236 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#240 Bump Contour to v1.8.1
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  pkg/reconciler/contour/resources/kingress.go
  pkg/reconciler/contour/resources/kingress_test.go
  vendor/github.com/projectcontour/contour/cmd/contour/serve.go
  vendor/github.com/projectcontour/contour/internal/k8s/statusupdater.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#244 Try using kind for conformance
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  test/conformance/ingress_test.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#246 Adjust the default RetryOn policy.
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, cla: yes, lgtm, size/L

#247 Ensure that endpoint probes avoid hostname collisions.
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/kingress.go
  pkg/reconciler/contour/resources/kingress_test.go
Labels: approved, cla: yes, lgtm, size/M

#249 Add linting config and fix issues.
  .golangci.yaml
  pkg/reconciler/contour/config/contour_test.go
Labels: approved, cla: yes, lgtm, size/S

#250 Use RetryTestErrors
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#251 Pull in Get retries
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#254 Resume building Contour from source
  config/contour/external.yaml
  config/contour/internal.yaml
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/S

#257 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#256 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#259 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#261 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#262 enable code coverage
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#264 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#265 Revert "[master] Auto-update dependencies"
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#263 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#266 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#268 [master] Update GitHub Actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#270 Update the golangci-lint definition from serving
  .golangci.yaml
Labels: approved, cla: yes, lgtm, size/S

#269 [Release-0.18] Pin deps to release-0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#271 Run the three versions of KinD used in Serving
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/M

#272 Add back presubmit (oops), and add cron.
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/M

#273 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#274 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#277 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#278 Start testing with multi-arch
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#279 Dedup the working-directory run setting
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#280 Fix the t formatter calls
  pkg/reconciler/contour/config/contour_test.go
  pkg/reconciler/contour/config/store_test.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/lister_test.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  pkg/reconciler/contour/resources/kingress_test.go
Labels: approved, cla: yes, lgtm, size/S

#281 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#284 Make codeconv settings uniform with other repos
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/S

#285 Publish multi-arch during CI
  hack/release.sh
  test/e2e-common.sh
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/S

#286 Drop --strict from ko
  hack/release.sh
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/XS
