Repository knative-extensions/net-contour, pull requests merged in 2020-08, with the labels that each got.

#183 Improve the net-contour logging story.
  go.mod
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/resources/kingress.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#184 Fix a bad assumption in the HTTP Proxy logic.
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/resources/constants.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, cla: yes, lgtm, size/M

#185 Disable endpoint probing with path prefixes.
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/kingress.go
  pkg/reconciler/contour/resources/kingress_test.go
Labels: approved, cla: yes, lgtm, size/M

#186 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/config/defaults.go
  vendor/knative.dev/networking/pkg/apis/config/doc.go
  vendor/knative.dev/networking/pkg/apis/config/store.go
  vendor/knative.dev/networking/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#191 Avoid updates due to defaulting.
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/kingress.go
  pkg/reconciler/contour/resources/kingress_test.go
Labels: approved, cla: yes, lgtm, size/M

#193 Allow operators to setup a default certificate
  config/config-contour.yaml
  pkg/reconciler/contour/config/contour.go
  pkg/reconciler/contour/config/contour_test.go
  pkg/reconciler/contour/config/zz_generated.deepcopy.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, cla: yes, lgtm, size/L

#195 Have Envoy emit debug logs
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#196 Prefer nil over empty list in LoadBalancer field
  pkg/reconciler/contour/contour.go
Labels: approved, cla: yes, lgtm, size/XS

#197 Pin some knative deps to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#198 Turn it up to 11, literally.
  test/conformance/ingress_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#199 Pull in the 404 cherrypick to bake
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/hosts.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#201 Pull in networking CPs to further stabilize.
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#206 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#208 Pull in test-infra for DNS cache
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#205 Fixes #204 - actually parse the correct property & fix the unit tests
  pkg/reconciler/contour/config/contour.go
  pkg/reconciler/contour/config/contour_test.go
Labels: approved, cla: yes, lgtm, size/S

#212 Enable conformance tests for tags.
  test/conformance/ingress_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#215 Add log decoration to give more context at the log site.
  pkg/reconciler/contour/contour.go
Labels: approved, cla: yes, lgtm, size/M

#213 Plumb through RewriteHost in the obvious way.
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, cla: yes, lgtm, size/M

#216 Remove knative.dev/serving deps and update the other deps
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/networking/test/conformance/ingress/rewrite.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#217 Unpin net-contour
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/probe_handler.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/hosts.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/rewrite.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/kmp/diff.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#218 Import networking#102
  go.mod
  go.sum
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#224 Configure default retries matching Istio
  go.mod
  go.sum
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#225 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#227 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#229 Fix go vet issues
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  pkg/reconciler/contour/resources/kingress_test.go
Labels: approved, cla: yes, lgtm, size/S

#230 Revert to 1.4
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/system/testing/names.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#231 Avoid thundering herd of probes during failover.
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
Labels: approved, cla: yes, lgtm, size/M

#234 Drop -parallel
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS
