Repository knative-extensions/net-contour, pull requests merged in 2020-04, with the labels that each got.

#87 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.toml
  vendor/knative.dev/serving/test/apicoverage/image/common/common.go
  vendor/knative.dev/serving/test/conformance/runtime/cgroup_test.go
  vendor/knative.dev/serving/test/conformance/runtime/cmd_args_test.go
  vendor/knative.dev/serving/test/conformance/runtime/container_test.go
  vendor/knative.dev/serving/test/conformance/runtime/envpropagation_test.go
  vendor/knative.dev/serving/test/conformance/runtime/envvars_test.go
  vendor/knative.dev/serving/test/conformance/runtime/protocol_test.go
  vendor/knative.dev/serving/test/conformance/runtime/readiness_probe_test.go
  vendor/knative.dev/serving/test/conformance/runtime/user_test.go
  vendor/knative.dev/serving/test/conformance/runtime/util.go
  vendor/knative.dev/serving/test/conformance/runtime/workingdir_test.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/performance/benchmarks/scale-from-zero/continuous/main.go
  vendor/knative.dev/serving/test/performance/observed_concurency_test.go
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#93 Manually update deps.
  Gopkg.lock
  pkg/reconciler/contour/resources/httpproxy_test.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/performance/performance.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/pkg/activator/net/revision_backends.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/leaderelection/config.go
  vendor/knative.dev/serving/pkg/leaderelection/testdata/config-leader-election.yaml
  vendor/knative.dev/serving/pkg/network/ingress/ingress.go
  vendor/knative.dev/serving/pkg/network/status/status.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/scaler.go
  vendor/knative.dev/serving/test/apicoverage.sh
  vendor/knative.dev/serving/test/apicoverage/tools/main.go
  vendor/knative.dev/serving/test/clients.go
  vendor/knative.dev/serving/test/config/security/policy.yaml
  vendor/knative.dev/serving/test/conformance/ingress/update_test.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/knative.dev/serving/test/ha/autoscalerhpa_test.go
  vendor/knative.dev/serving/test/ha/controller_test.go
  vendor/knative.dev/serving/test/ha/ha.go
  vendor/knative.dev/serving/test/performance/benchmarks/dataplane-probe/continuous/main.go
  vendor/knative.dev/serving/test/performance/latency_test.go
  vendor/knative.dev/serving/test/performance/observed_concurency_test.go
  vendor/knative.dev/serving/test/performance/performance-tests.sh
  vendor/knative.dev/serving/test/performance/scale_test.go
  vendor/knative.dev/serving/test/system.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XL

#91 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/pkg/network/ingress/ingress.go
  vendor/knative.dev/serving/test/performance/performance-tests.sh
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
Labels: approved, cla: yes, lgtm, size/M

#94 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/delete.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/knative.dev/pkg/testutils/metahelper/main.go
  vendor/knative.dev/serving/pkg/autoscaler/metrics/collector.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/kpa.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#95 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/cmd/default-domain/main.go
  vendor/knative.dev/serving/pkg/activator/handler/handler.go
  vendor/knative.dev/serving/pkg/activator/net/throttler.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/hpa/controller.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/hpa/hpa.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/controller.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/reconciler.go
  vendor/knative.dev/serving/pkg/reconciler/certificate/certificate.go
  vendor/knative.dev/serving/pkg/reconciler/route/route.go
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/controller.go
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/subsetter.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/XXL

#97 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/images/Knative-Duck0.png
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/serving/DEVELOPMENT.md
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.toml
  vendor/knative.dev/serving/cmd/queue/main.go
  vendor/knative.dev/serving/pkg/autoscaler/metrics/collector.go
  vendor/knative.dev/serving/pkg/reconciler/metric/controller.go
  vendor/knative.dev/serving/pkg/reconciler/metric/metric.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/deploy.go
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/subsetter.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
Labels: approved, cla: yes, lgtm, size/XL

#98 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/deploy.go
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/serverlessservice.go
  vendor/knative.dev/serving/pkg/testing/functional.go
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/upgrade/service_postupgrade_test.go
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#99 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/serving/DEVELOPMENT.md
  vendor/knative.dev/serving/config/core/resources/serverlessservice.yaml
  vendor/knative.dev/serving/config/core/roles/clusterrole.yaml
  vendor/knative.dev/serving/config/post-install/storage-version-migration.yaml
  vendor/knative.dev/serving/hack/generate-yamls.sh
  vendor/knative.dev/serving/test/conformance/ingress/util.go
  vendor/knative.dev/serving/test/ha/autoscalerhpa_test.go
  vendor/knative.dev/serving/test/ha/controller_test.go
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#90 Remove duplicate cluster role binding definitions
  config/contour/external.yaml
  config/contour/internal.yaml
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/M

#100 Unskip TestVisibility (should be fixed).
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#101 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/config/core/configmaps/autoscaler.yaml
  vendor/knative.dev/serving/config/monitoring/metrics/prometheus/100-grafana-dash-knative-scaling.yaml
  vendor/knative.dev/serving/config/monitoring/metrics/prometheus/100-grafana-dash-knative.yaml
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/kpa.go
  vendor/knative.dev/serving/pkg/reconciler/revision/revision.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/ha/activator_test.go
  vendor/knative.dev/serving/test/ha/autoscalerhpa_test.go
  vendor/knative.dev/serving/test/ha/controller_test.go
  vendor/knative.dev/serving/test/ha/ha.go
  vendor/knative.dev/serving/test/performance/benchmarks/deployment-probe/continuous/main.go
  vendor/knative.dev/serving/third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/deployment-dashboard.json
  vendor/knative.dev/serving/third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/pods-dashboard.json
  vendor/knative.dev/serving/third_party/config/monitoring/metrics/prometheus/prometheus-operator/dashboards/statefulset-dashboard.json
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/download-istio.sh
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-ci-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-ci-no-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-crds.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-knative-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/istio-minimal.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/values-lean.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.6/values.yaml
  vendor/knative.dev/serving/third_party/istio-1.5-latest
  vendor/knative.dev/serving/third_party/istio-1.5.0/README.md
  vendor/knative.dev/serving/third_party/istio-1.5.0/download-istio.sh
  vendor/knative.dev/serving/third_party/istio-1.5.0/drain-seconds.yaml.patch
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-ci-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-ci-no-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-crds.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-knative-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/istio-minimal.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/namespace.yaml.patch
  vendor/knative.dev/serving/third_party/istio-1.5.0/values-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/values-lean.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/values-local.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.0/values.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.1/README.md
  vendor/knative.dev/serving/third_party/istio-1.5.1/generate.sh
  vendor/knative.dev/serving/third_party/istio-1.5.1/istio-ci-mesh-operator.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.1/istio-ci-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.1/istio-ci-no-mesh-operator.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.1/istio-ci-no-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.1/istio-crds.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.1/istio-minimal-operator.yaml
  vendor/knative.dev/serving/third_party/istio-1.5.1/istio-minimal.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#103 Add wait for LB call
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#104 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/Gopkg.toml
  vendor/knative.dev/serving/cmd/queue/main.go
  vendor/knative.dev/serving/cmd/queue/main_test.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/istio-1.4-latest
  vendor/knative.dev/serving/third_party/istio-1.4.7/README.md
  vendor/knative.dev/serving/third_party/istio-1.4.7/download-istio.sh
  vendor/knative.dev/serving/third_party/istio-1.4.7/drain-seconds.yaml.patch
  vendor/knative.dev/serving/third_party/istio-1.4.7/istio-ci-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.7/istio-ci-no-mesh.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.7/istio-crds.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.7/istio-knative-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.7/istio-minimal.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.7/namespace.yaml.patch
  vendor/knative.dev/serving/third_party/istio-1.4.7/values-extras.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.7/values-lean.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.7/values-local.yaml
  vendor/knative.dev/serving/third_party/istio-1.4.7/values.yaml
  vendor/knative.dev/serving/third_party/istio-stable
  vendor/knative.dev/serving/third_party/net-istio.yaml
Labels: approved, cla: yes, lgtm, size/L

#105 Freeze deps for 0.14
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/OWNERS_ALIASES
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/serving/cmd/queue/main.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#106 Run net-contour as non-root
  .ko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#110 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/injection/context.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/prober/prober.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/message.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/ignorefields.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/OWNERS_ALIASES
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/kpa.go
  vendor/knative.dev/serving/pkg/reconciler/certificate/controller.go
  vendor/knative.dev/serving/pkg/reconciler/route/controller.go
  vendor/knative.dev/serving/pkg/resources/endpoints.go
  vendor/knative.dev/serving/pkg/resources/pods.go
  vendor/knative.dev/serving/test/conformance/ingress/grpc_test.go
  vendor/knative.dev/serving/third_party/kourier-latest/kourier.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XL

#111 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/go.mod
  vendor/knative.dev/pkg/go.sum
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hack/verify-codegen.sh
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/ghutil/fakeghutil/fakeghutil.go
  vendor/knative.dev/pkg/test/ghutil/issue.go
  vendor/knative.dev/pkg/test/ghutil/pullrequest.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/cmd/activator/main.go
  vendor/knative.dev/serving/cmd/autoscaler/main.go
  vendor/knative.dev/serving/cmd/queue/main.go
  vendor/knative.dev/serving/cmd/queue/main_test.go
  vendor/knative.dev/serving/pkg/activator/handler/concurrency_reporter.go
  vendor/knative.dev/serving/pkg/activator/handler/metrics.go
  vendor/knative.dev/serving/pkg/activator/handler/requestevent_handler.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/autoscaler/metrics/stats_scraper.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/pkg/queue/stats.go
  vendor/knative.dev/serving/pkg/reconciler/revision/cruds.go
  vendor/knative.dev/serving/pkg/reconciler/revision/reconcile_resources.go
  vendor/knative.dev/serving/pkg/reconciler/revision/resources/imagecache.go
  vendor/knative.dev/serving/pkg/reconciler/route/route.go
  vendor/knative.dev/serving/pkg/resources/pods.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/knative.dev/serving/pkg/webhook/validate_service.go
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/serving/third_party/kourier-latest/kourier.yaml
  vendor/knative.dev/serving/third_party/net-istio.yaml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XXL
