Repository knative-extensions/net-contour, pull requests merged in 2020-02, with the labels that each got.

#16 Add a release script to get nightly releases.
  hack/release.sh
Labels: approved, lgtm, size/M

#17 Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/S

#22 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/serving/.github/pull-request-template.md
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/cmd/autoscaler/main.go
  vendor/knative.dev/serving/config/activator-ds.yaml
  vendor/knative.dev/serving/config/core/activator-ds.yaml
  vendor/knative.dev/serving/config/core/deployments/activator-hpa.yaml
  vendor/knative.dev/serving/config/core/deployments/activator.yaml
  vendor/knative.dev/serving/pkg/activator/handler/handler.go
  vendor/knative.dev/serving/pkg/activator/handler/metric_handler.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/service_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/autoscaler.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/stats_reporter.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/reconciler.go
  vendor/knative.dev/serving/pkg/reconciler/certificate/certificate.go
  vendor/knative.dev/serving/pkg/reconciler/configuration/configuration.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/ingress.go
  vendor/knative.dev/serving/pkg/reconciler/ingress/resources/names/names.go
  vendor/knative.dev/serving/pkg/reconciler/metric/metric.go
  vendor/knative.dev/serving/pkg/reconciler/retry.go
  vendor/knative.dev/serving/pkg/reconciler/revision/revision.go
  vendor/knative.dev/serving/pkg/reconciler/route/reconcile_resources.go
  vendor/knative.dev/serving/pkg/reconciler/serverlessservice/serverlessservice.go
  vendor/knative.dev/serving/pkg/reconciler/service/service.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/performance/performance-tests.sh
  vendor/knative.dev/serving/third_party/contour-latest/README.md
  vendor/knative.dev/serving/third_party/contour-latest/contour.yaml
  vendor/knative.dev/serving/third_party/contour-latest/net-contour.yaml
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XXL

#28 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/cmd/activator/main.go
  vendor/knative.dev/serving/pkg/activator/handler/concurrency_reporter.go
  vendor/knative.dev/serving/pkg/activator/handler/metric_handler.go
  vendor/knative.dev/serving/pkg/activator/handler/metrics.go
  vendor/knative.dev/serving/pkg/activator/stats_reporter.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  vendor/knative.dev/serving/pkg/reconciler/configuration/configuration.go
  vendor/knative.dev/serving/pkg/reconciler/configuration/controller.go
  vendor/knative.dev/serving/pkg/reconciler/configuration/resources/revision.go
  vendor/knative.dev/serving/pkg/reconciler/route/route.go
  vendor/knative.dev/serving/pkg/reconciler/service/service.go
  vendor/knative.dev/serving/pkg/testing/v1/configuration.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/route.go
  vendor/knative.dev/serving/pkg/testing/v1alpha1/service.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, lgtm, size/XL

#34 Take config-network HTTPProtocol in consideration when listing targets
  pkg/reconciler/contour/config/store.go
  pkg/reconciler/contour/config/zz_generated.deepcopy.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/lister.go
  pkg/reconciler/contour/lister_test.go
Labels: approved, lgtm, ok-to-test, size/M

#36 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/serving/Gopkg.lock
  vendor/knative.dev/serving/cmd/activator/main.go
  vendor/knative.dev/serving/pkg/activator/handler/concurrency_reporter.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/serving/pkg/autoscaler/scaling/autoscaler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/metric/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/autoscaling/v1alpha1/podautoscaler/stub/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/certificate/stub/controller.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/networking/v1alpha1/serverlessservice/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/serving/v1/configuration/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/serving/v1/revision/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/serving/v1/route/reconciler.go
  vendor/knative.dev/serving/pkg/client/injection/reconciler/serving/v1alpha1/configuration/reconciler.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/hpa/controller.go
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/kpa/controller.go
  vendor/knative.dev/serving/pkg/reconciler/certificate/controller.go
  vendor/knative.dev/serving/pkg/reconciler/nscert/nscert.go
  vendor/knative.dev/serving/pkg/reconciler/nscert/resources/wildcard_certificate.go
  vendor/knative.dev/serving/test/config/autotls/certmanager/http01/issuer.yaml
  vendor/knative.dev/serving/test/e2e-auto-tls.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e/autotls/README.md
  vendor/knative.dev/serving/test/e2e/autotls/config/disablenscert/main.go
  vendor/knative.dev/serving/test/e2e/websocket.go
Labels: approved, lgtm, size/XXL

#38 Fix the image rewrite, so it actually rewrites
  config/contour/external.yaml
  config/contour/internal.yaml
  hack/update-deps.sh
Labels: approved, lgtm, size/S

#43 Fix broken markdown link
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS
