Repository knative-extensions/net-contour, pull requests merged in 2021-03, with the labels that each got.

#437 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/clock.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L

#438 Consolidate lines in CODEOWNERS, drop hack/test
  .github/CODEOWNERS
Labels: cla: yes, lgtm, size/S

#439 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L

#440 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S

#441 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/XS

#442 Fix typo in config-contour example
  config/config-contour.yaml
Labels: cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#443 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#445 Run all actions against main
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, lgtm, size/XS

#444 use tmpfs for etcd storage to avoid timeouts
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, kind/cleanup, lgtm, size/S

#447 Drop master references to knative repos
  DEVELOPMENT.md
  hack/release.sh
Labels: cla: yes, lgtm, size/XS

#446 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, size/XS

#448 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#449 Clarify that rule paths should be prefix matched
  pkg/reconciler/contour/resources/httpproxy.go
Labels: cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#450 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/networking/pkg/apis/networking/generic_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/test/conformance/ingress/README.md
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#451 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, size/XS

#452 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/client/client.go
  vendor/knative.dev/networking/pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L

#454 Use new filter function constructors
  pkg/reconciler/contour/controller.go
Labels: cla: yes, kind/cleanup, lgtm, size/XS

#457 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: cla: yes, lgtm, size/XS

#458 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L

#459 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#461 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#460 Replace copied ingress CRD with link to networking one
  hack/tools.go
  test/config/300-ingress.yaml
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/placeholder.go
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#463 Update actions and deps manually
  .github/workflows/knative-releasability.yaml
  go.sum
Labels: cla: yes, lgtm, size/L

#466 bump contour to 1.13.1
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/github.com/projectcontour/contour/cmd/contour/ingressstatus.go
  vendor/github.com/projectcontour/contour/internal/k8s/statusaddress.go
  vendor/github.com/projectcontour/contour/internal/xdscache/v3/route.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/modules.txt
Labels: cla: yes, kind/bug, lgtm, size/M

#467 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/README.md
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S

#468 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S
