Repository knative-extensions/net-contour, pull requests merged in 2021-09, with the labels that each got.

#601 Add some more newb friendly local dev blurb to DEVELOPMENT.MD
  DEVELOPMENT.md
Labels: approved, lgtm, size/S, cla: yes

#602 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#603 drop scheduled actions these fill up the job queue causing delays
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/XS, cla: yes

#604 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#608 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#609 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, cla: yes

#611 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, cla: yes

#612 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#613 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#614 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#610 Support HTTPOption in Ingress spec
  .github/workflows/kind-e2e.yaml
  pkg/reconciler/contour/config/store.go
  pkg/reconciler/contour/config/store_test.go
  pkg/reconciler/contour/config/zz_generated.deepcopy.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/lister.go
  pkg/reconciler/contour/lister_test.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  pkg/reconciler/contour/resources/kingress.go
  pkg/reconciler/contour/resources/kingress_test.go
  test/config/config-network.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/L, cla: yes

#615 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/test/conformance/ingress/httpoption.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#616 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, cla: yes

#618 Drop K8s 1.19 as it's no longer supported
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/S, cla: yes

#620 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/S, cla: yes

#619 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#617 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#621 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS, cla: yes

#622 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#623 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#624 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/S, cla: yes

#625 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#629 pin go-control-plane so contour continues to build
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes
