Repository knative-extensions/net-contour, pull requests merged in 2021-07, with the labels that each got.

#542 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#541 [main] Update actions
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#543 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#544 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#545 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#547 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#548 Fix typo
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS

#540 Move from using sed to use ytt in the update-deps script
  config/contour/external.yaml
  config/contour/internal.yaml
  hack/overlays/add-ingress-provider-label.yaml
  hack/overlays/clusterrolebindings.yaml
  hack/overlays/delete-contour-clusterrolebinding.yaml
  hack/overlays/disable-envoy-daemonset-hostport.yaml
  hack/overlays/rename-contour-clusterrole.yaml
  hack/overlays/rename-contour-namespace.yaml
  hack/overlays/rewrite-contour-command.yaml
  hack/overlays/rewrite-contour-image.yaml
  hack/overlays/rewrite-contour-pod-security-context.yaml
  hack/overlays/rewrite-envoy-daemonset-command.yaml
  hack/overlays/rewrite-envoy-service-type.yaml
  hack/overlays/values.yaml
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#550 Use const value for `projectcontour.io/ingress.class`
  pkg/reconciler/contour/resources/kingress.go
Labels: approved, cla: yes, lgtm, size/XS

#552 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/buffered_write_syncer.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/typeparams/doc.go
  vendor/golang.org/x/tools/internal/typeparams/notypeparams.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#551 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#553 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#554 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#557 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#556 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#558 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#559 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#560 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#561 Remove `DeprecatedRetries` from unit test
  pkg/reconciler/contour/resources/kingress_test.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS
