Repository knative-extensions/net-contour, pull requests merged in 2021-08, with the labels that each got.

#568 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#569 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#570 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#573 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#572 Bump Golang version to 1.16
  .github/workflows/kind-e2e.yaml
  go.mod
Labels: approved, lgtm, size/XS, cla: yes

#579 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, cla: yes

#580 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS, cla: yes

#578 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/projectcontour/v1/httpproxy/filtered/httpproxy.go
  pkg/client/injection/informers/projectcontour/v1/httpproxy/httpproxy.go
  pkg/client/injection/informers/projectcontour/v1/tlscertificatedelegation/filtered/tlscertificatedelegation.go
  pkg/client/injection/informers/projectcontour/v1/tlscertificatedelegation/tlscertificatedelegation.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/client/injection/client/client.go
  vendor/knative.dev/networking/pkg/client/injection/informers/networking/v1alpha1/ingress/ingress.go
  vendor/knative.dev/networking/test/conformance/ingress/rewrite.go
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/dynamicclient/dynamicclient.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, cla: yes

#581 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#583 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/modules.txt
Labels: approved, lgtm, size/L, cla: yes

#584 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/alecthomas/template/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-kit/log/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-logfmt/logfmt/LICENSE
  vendor/contrib.go.opencensus.io/exporter/prometheus/go.mod
  vendor/contrib.go.opencensus.io/exporter/prometheus/go.sum
  vendor/github.com/go-kit/log/.gitignore
  vendor/github.com/go-kit/log/LICENSE
  vendor/github.com/go-kit/log/README.md
  vendor/github.com/go-kit/log/doc.go
  vendor/github.com/go-kit/log/go.mod
  vendor/github.com/go-kit/log/go.sum
  vendor/github.com/go-kit/log/json_logger.go
  vendor/github.com/go-kit/log/level/doc.go
  vendor/github.com/go-kit/log/level/level.go
  vendor/github.com/go-kit/log/log.go
  vendor/github.com/go-kit/log/logfmt_logger.go
  vendor/github.com/go-kit/log/nop_logger.go
  vendor/github.com/go-kit/log/stdlib.go
  vendor/github.com/go-kit/log/sync.go
  vendor/github.com/go-kit/log/value.go
  vendor/github.com/go-logfmt/logfmt/.gitignore
  vendor/github.com/go-logfmt/logfmt/.travis.yml
  vendor/github.com/go-logfmt/logfmt/CHANGELOG.md
  vendor/github.com/go-logfmt/logfmt/LICENSE
  vendor/github.com/go-logfmt/logfmt/README.md
  vendor/github.com/go-logfmt/logfmt/decode.go
  vendor/github.com/go-logfmt/logfmt/doc.go
  vendor/github.com/go-logfmt/logfmt/encode.go
  vendor/github.com/go-logfmt/logfmt/go.mod
  vendor/github.com/go-logfmt/logfmt/jsonstring.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/common/log/eventlog_formatter.go
  vendor/github.com/prometheus/common/log/log.go
  vendor/github.com/prometheus/common/log/syslog_formatter.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/fsm/fsm.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapper.go
  vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapper_cache.go
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/mksyscall.go
  vendor/golang.org/x/sys/windows/registry/syscall.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go
  vendor/golang.org/x/sys/windows/svc/eventlog/install.go
  vendor/golang.org/x/sys/windows/svc/eventlog/log.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, cla: yes

#585 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#586 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#598 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes
