Repository knative-extensions/net-contour, pull requests merged in 2021-10, with the labels that each got.

#636 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, cla: yes

#627 HTTP External Auth Support
  pkg/reconciler/contour/resources/constants.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, lgtm, size/L, cla: yes, kind/enhancement

#642 [main] Format Go code
  hack/tools.go
  test/conformance/ingress_test.go
Labels: approved, lgtm, size/XS, cla: yes
