Repository knative-extensions/net-contour, pull requests merged in 2021-02, with the labels that each got.

#411 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#413 Drop multi-arch builds on actions.
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#415 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#416 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#419 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#420 Try dropping OWNER files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#421 Use sigs.k8s.io/yaml for YAML operations
  go.mod
  pkg/reconciler/contour/config/contour.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#424 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#425 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#426 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#427 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#428 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#429 Update the year in boilerplate.*.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.sh.txt
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/doc.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/fake/fake_httpproxy.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/fake/fake_projectcontour_client.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/fake/fake_tlscertificatedelegation.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/httpproxy.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/projectcontour_client.go
  pkg/client/clientset/versioned/typed/projectcontour/v1/tlscertificatedelegation.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/projectcontour/interface.go
  pkg/client/informers/externalversions/projectcontour/v1/httpproxy.go
  pkg/client/informers/externalversions/projectcontour/v1/interface.go
  pkg/client/informers/externalversions/projectcontour/v1/tlscertificatedelegation.go
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  pkg/client/injection/informers/factory/factory.go
  pkg/client/injection/informers/factory/fake/fake.go
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/projectcontour/v1/httpproxy/fake/fake.go
  pkg/client/injection/informers/projectcontour/v1/httpproxy/filtered/fake/fake.go
  pkg/client/injection/informers/projectcontour/v1/httpproxy/filtered/httpproxy.go
  pkg/client/injection/informers/projectcontour/v1/httpproxy/httpproxy.go
  pkg/client/injection/informers/projectcontour/v1/tlscertificatedelegation/fake/fake.go
  pkg/client/injection/informers/projectcontour/v1/tlscertificatedelegation/filtered/fake/fake.go
  pkg/client/injection/informers/projectcontour/v1/tlscertificatedelegation/filtered/tlscertificatedelegation.go
  pkg/client/injection/informers/projectcontour/v1/tlscertificatedelegation/tlscertificatedelegation.go
  pkg/client/listers/projectcontour/v1/expansion_generated.go
  pkg/client/listers/projectcontour/v1/httpproxy.go
  pkg/client/listers/projectcontour/v1/tlscertificatedelegation.go
  pkg/reconciler/contour/config/zz_generated.deepcopy.go
Labels: cla: yes, lgtm, size/XS

#430 use net-contour approvers group in CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, lgtm, size/XS

#431 update badge to point to pkg.go.dev
  README.md
Labels: cla: yes, lgtm, size/XS

#432 [Automated] Fix misspellings
  .github/CODEOWNERS
Labels: cla: yes, lgtm, size/XS

#434 Add release-leads to CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, lgtm, size/XS

#435 Bump k8s version in kind e2e
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, kind/cleanup, lgtm, size/S
