Repository knative-extensions/net-contour, pull requests merged in 2021-01, with the labels that each got.

#395 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#396 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#397 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#398 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#399 Add a CODEOWNERS to experiment with different review gating.
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#400 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#406 Add a missing godoc comment
  pkg/reconciler/contour/resources/kingress.go
Labels: approved, cla: yes, lgtm, size/XS

#404 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/projectcontour/v1/httpproxy/filtered/fake/fake.go
  pkg/client/injection/informers/projectcontour/v1/httpproxy/filtered/httpproxy.go
  pkg/client/injection/informers/projectcontour/v1/tlscertificatedelegation/filtered/fake/fake.go
  pkg/client/injection/informers/projectcontour/v1/tlscertificatedelegation/filtered/tlscertificatedelegation.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#407 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/generators/tags.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/serverlessservice.go
  vendor/knative.dev/networking/test/conformance/ingress/run.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#408 fix logstream
  test/config/config-logging.yaml
Labels: approved, cla: yes, lgtm, size/XS
