Repository knative-extensions/net-contour, pull requests merged in 2022-06, with the labels that each got.

#767 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#768 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#769 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#770 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#771 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#772 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#773 bump kind and k8s versions for v1.24
  .github/workflows/kind-e2e-nightly.yaml
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/M

#775 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#774 Updates for deprecated network dependencies
  pkg/reconciler/contour/controller.go
  pkg/reconciler/contour/controller_test.go
  pkg/reconciler/contour/lister.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#776 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review
