Repository knative-extensions/net-contour, pull requests merged in 2022-12, with the labels that each got.

#819 net-contour supports `internal encryption` configuration
  config/secret-delegation.yaml
  go.mod
  go.sum
  pkg/reconciler/contour/config/store.go
  pkg/reconciler/contour/config/store_test.go
  pkg/reconciler/contour/config/testdata/config-network.yaml
  pkg/reconciler/contour/config/zz_generated.deepcopy.go
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/constants.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  test/config/config-network.yaml
  third_party/VENDOR-LICENSE/knative.dev/control-protocol/pkg/certificates/LICENSE
  vendor/cloud.google.com/go/compute/LICENSE
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/knative.dev/control-protocol/LICENSE
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/control-protocol/pkg/certificates/constants.go
  vendor/knative.dev/control-protocol/pkg/certificates/key_pair.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm, ok-to-test, kind/enhancement

#836 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#837 [release-1.8] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: approved, lgtm, size/XS

#838 [release-1.7] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: approved, lgtm, size/XS

#839 [release-1.6] Rebuild using Go 1.19.4 (to address CVEs)
  go.mod
Labels: approved, lgtm, size/XS

#840 [release-1.8] gofmt with go1.19
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: approved, lgtm, size/XS

#841 [release-1.7] gofmt with go1.19
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: approved, lgtm, size/XS

#842 [release-1.6] gofmt with go1.19
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: approved, lgtm, size/XS

#844 Add app.k8s.io labels to the deployment - not just the pod template
  config/controller.yaml
Labels: approved, lgtm, size/XS

#845 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#846 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
