Repository knative-extensions/net-contour, pull requests merged in 2022-07, with the labels that each got.

#778 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#779 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#777 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#780 bump contour to v1.21.1
  config/contour-operator/operator.yaml
  config/contour/external.yaml
  config/contour/internal.yaml
  hack/overlays/rename-contour-namespace.yaml
  hack/update-deps.sh
Labels: size/XXL, approved, lgtm

#781 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/.travis.yml
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/projectcontour/contour/apis/projectcontour/v1/httpproxy.go
  vendor/github.com/projectcontour/contour/apis/projectcontour/v1/zz_generated.deepcopy.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/credentials/insecure/insecure.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/transport/flowcontrol.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/proxy.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#783 drop git info from kodata
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/refs
Labels: approved, lgtm, size/XS

#782 Drop use of the contour operator
  .github/workflows/kind-e2e-nightly.yaml
  .github/workflows/kind-e2e.yaml
  config/contour-operator/gateway-external.yaml
  config/contour-operator/gateway-internal.yaml
  config/contour-operator/operator.yaml
  hack/update-deps.sh
Labels: size/XXL, approved, lgtm

#787 Bump Go version to 1.18 for CI
  .github/workflows/kind-e2e-nightly.yaml
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/XS

#789 Bump go.mod to v1.18
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#788 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/language/common.go
  vendor/golang.org/x/text/internal/language/compact.go
  vendor/golang.org/x/text/internal/language/compact/compact.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/compact/parents.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/compact/tags.go
  vendor/golang.org/x/text/internal/language/compose.go
  vendor/golang.org/x/text/internal/language/coverage.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/match.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/language/tags.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tag/tag.go
  vendor/golang.org/x/text/language/coverage.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/language/tags.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#790 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/pkg/pool/doc.go
  vendor/knative.dev/pkg/pool/interface.go
  vendor/knative.dev/pkg/pool/pool.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#792 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#791 fix the release script
  hack/release.sh
Labels: approved, lgtm, size/XS
