Repository knative-extensions/net-contour, pull requests merged in 2022-03, with the labels that each got.

#731 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/S

#732 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#733 Rename certgen job in nightly build CI
  .github/workflows/kind-e2e-nightly.yaml
Labels: approved, lgtm, ok-to-test, size/XS, kind/cleanup

#734 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#736 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#737 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#740 Adding code of conduct to reference knative/community's CoC
  code-of-conduct.md
Labels: approved, lgtm, size/M

#744 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/XL
