Repository knative-extensions/net-contour, pull requests merged in 2022-10, with the labels that each got.

#816 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, skip-review

#817 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS, skip-review

#818 Bump k8s version in kind
  .github/workflows/kind-e2e-nightly.yaml
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/M

#722 Update documentation with e2e testing instructions for kind
  DEVELOPMENT.md
Labels: approved, lgtm, size/L

#820 [main] Format markdown
  DEVELOPMENT.md
  code-of-conduct.md
Labels: approved, lgtm, size/XS

#821 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#822 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#823 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
