Repository knative-extensions/net-contour, pull requests merged in 2022-04, with the labels that each got.

#741 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#742 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#746 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#747 drop knative.dev/release label
  config/config-contour.yaml
  hack/release.sh
  test/config/200-service-account.yaml
  test/config/chaosduck.yaml
Labels: approved, lgtm, size/S

#750 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#751 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#754 Bump k8s version in KinD
  .github/workflows/kind-e2e-nightly.yaml
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/M

#749 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#756 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
