Repository knative-extensions/net-contour, pull requests merged in 2022-11, with the labels that each got.

#824 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#828 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#829 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/cgroup.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/file_access_attempt.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/knative.dev/networking/test/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#830 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#832 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#831 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#834 drop string literal must be 'ALL'
  config/controller.yaml
Labels: approved, lgtm, size/XS

#833 refactor actions to use e2e scripts
  .github/workflows/kind-e2e-nightly.yaml
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/XL, kind/cleanup
