Repository knative-extensions/net-contour, pull requests merged in 2023-09, with the labels that each got.

#949 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#950 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#951 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#952 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#955 add seccompProfile to controller
  config/controller.yaml
Labels: approved, lgtm, size/XS

#957 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#959 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/M

#963 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#966 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#965 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#968 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#969 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#967 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#970 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#971 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
