Repository knative-extensions/net-contour, pull requests merged in 2023-10, with the labels that each got.

#958 use new encryption flags from https://github.com/knative/networking/pull/858
  go.mod
  go.sum
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#975 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#976 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#978 [release-1.10] Rebuild using Go 1.20.10 (to address CVEs)
  go.mod
Labels: approved, lgtm, size/XS

#977 fix: Bump Go and Kind Versions
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#982 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#985 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#986 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#987 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#988 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#989 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#990 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#991 bump contour to v1.26.1
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#992 [release-1.11] bump contour to latest patch
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/github.com/imdario/mergo/README.md
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/golang.org/x/tools/internal/event/tag/tag.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#993 [release-1.10] bump contour to latest patch version
  config/contour/external.yaml
  config/contour/internal.yaml
  hack/update-deps.sh
Labels: approved, lgtm, size/L
