Repository knative-extensions/net-contour, pull requests merged in 2023-02, with the labels that each got.

#863 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#865 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#864 update OWNERS files
  OWNERS
Labels: approved, lgtm, size/XS

#866 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#867 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#869 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#871 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#870 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#872 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#860 Internal Encryption fixes
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/constants.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, lgtm, size/XL

#875 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#876 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#877 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#881 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/language/language.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#883 [release-1.9] trigger to build release with go1.19.6
  go.mod
Labels: approved, lgtm, size/XS
