Repository knative-extensions/net-contour, pull requests merged in 2023-01, with the labels that each got.

#847 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#851 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#853 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#852 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#854 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#855 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#856 When ingress visibility is ClusterLocal then permitInsecure
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, lgtm, size/L, kind/bug

#858 Add the correct labels to the TLSCertificateDelegation resource
  config/secret-delegation.yaml
Labels: approved, lgtm, size/XS
