Repository knative-extensions/net-contour, pull requests merged in 2023-12, with the labels that each got.

#1010 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1006 Filter IngressTLS for visibility IngressVisibilityExternalIP
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/kingress.go
  pkg/reconciler/contour/resources/kingress_test.go
Labels: approved, lgtm, size/S

#1013 [release-1.12] Bump to fix serving/#14732
  go.mod
Labels: approved, lgtm, size/XS

#1014 [release-1.11] Bump to fix serving/#14732
  go.mod
Labels: approved, lgtm, size/XS

#1012 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/SECURITY.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version6.go
  vendor/github.com/google/uuid/version7.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/event/keys/util.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm
