Repository knative-extensions/net-contour, pull requests merged in 2024-01, with the labels that each got.

#1016 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1017 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1019 Replace deprecated sets usages with generic version
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  pkg/reconciler/contour/config/contour.go
  pkg/reconciler/contour/config/zz_generated.deepcopy.go
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/lister.go
  pkg/reconciler/contour/lister_test.go
  pkg/reconciler/contour/resources/httpproxy.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/kflag/set.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, kind/cleanup

#1021 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1020 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1024 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1022 bump contour to v1.27.0
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/constants.go
  vendor/github.com/emicklei/go-restful/v3/request.go
  vendor/github.com/emicklei/go-restful/v3/response.go
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/github.com/projectcontour/contour/apis/projectcontour/v1/httpproxy.go
  vendor/k8s.io/gengo/args/args.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/namer.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/merge/conflict.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/merge/update.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/schema/elements.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/schema/schemaschema.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/typed.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/validate.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
Labels: approved, lgtm, size/XL

#1023 include k8s 1.29 in tests
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/XS

#1025 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/common/model/alert.go
  vendor/github.com/prometheus/common/model/metadata.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/github.com/prometheus/common/model/signature.go
  vendor/github.com/prometheus/common/model/silence.go
  vendor/github.com/prometheus/common/model/value.go
  vendor/github.com/prometheus/common/model/value_float.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/google.golang.org/protobuf/encoding/protodelim/protodelim.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#1027 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1028 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1029 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1030 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/context.go
  vendor/github.com/go-logr/logr/context_noslog.go
  vendor/github.com/go-logr/logr/context_slog.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr.go
  vendor/github.com/go-logr/logr/slogsink.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/version7.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL
