Repository knative-extensions/net-contour, pull requests merged in 2024-05, with the labels that each got.

#1083 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1086 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1085 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/encoding/tag/tag.go
  vendor/google.golang.org/protobuf/internal/errors/errors.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/placeholder.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  vendor/google.golang.org/protobuf/internal/impl/codec_map.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_enum.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_extension.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_file.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/messageset.go
  vendor/google.golang.org/protobuf/proto/size.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1088 Set CORS policy values only for when HTTPProxy associated with external visibility
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, lgtm, size/L, kind/cleanup

#1090 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1092 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, skip-review

#1095 Fix nil pointer dereference error when parsing config map
  pkg/reconciler/contour/config/contour.go
  pkg/reconciler/contour/config/contour_test.go
Labels: approved, lgtm, size/S, kind/bug

#1091 Bump Contour to version 1.29
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/github.com/projectcontour/contour/apis/projectcontour/v1/detailedconditions.go
  vendor/github.com/projectcontour/contour/apis/projectcontour/v1/httpproxy.go
  vendor/github.com/projectcontour/contour/apis/projectcontour/v1/register.go
  vendor/github.com/projectcontour/contour/apis/projectcontour/v1/tlscertificatedelegation.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, kind/enhancement

#1098 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
