Repository knative-extensions/net-contour, pull requests merged in 2024-06, with the labels that each got.

#1097 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1099 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1102 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1103 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#1101 use chainguard image
  .ko.yaml
Labels: approved, lgtm, size/XS

#1104 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1105 bump contour and k8s deps
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/github.com/go-logr/logr/README.md
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/encoding/text/decode.go
  vendor/google.golang.org/protobuf/internal/errors/errors.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filetype/build.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/impl/api_export.go
  vendor/google.golang.org/protobuf/internal/impl/checkinit.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_messageset.go
  vendor/google.golang.org/protobuf/internal/impl/convert.go
  vendor/google.golang.org/protobuf/internal/impl/convert_list.go
  vendor/google.golang.org/protobuf/internal/impl/convert_map.go
  vendor/google.golang.org/protobuf/internal/impl/encode.go
  vendor/google.golang.org/protobuf/internal/impl/extension.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_enum.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/order/range.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_pure.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/generators/markers.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/idl_tag.go
  vendor/k8s.io/kube-openapi/pkg/schemaconv/smd.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#1106 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1107 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/convert.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1108 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/kind2resource.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/filter.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/format-code.sh
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
