Repository knative-extensions/net-contour, pull requests merged in 2024-04, with the labels that each got.

#1066 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1067 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1070 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1071 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1073 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1072 Bump Contour to v1.28.2
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1074 Bump Contour to v1.28.3
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1075 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/httpoption.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/knative.dev/networking/test/ingress.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/networking/test/test_images/runtime/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1079 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1078 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1080 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1081 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1082 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
