Repository knative-extensions/net-contour, pull requests merged in 2024-07, with the labels that each got.

#1109 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1110 fix system internal encryption
  config/secret-delegation.yaml
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, lgtm, size/M

#1111 Default TLS certificate shouldn't be applied to cluster local routes
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, lgtm, size/L

#1113 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_asm.go
  vendor/github.com/cespare/xxhash/v2/xxhash_other.go
  vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand_go1.21.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#1114 fix boilerplate
  pkg/reconciler/contour/config/contour.go
  pkg/reconciler/contour/config/contour_test.go
  pkg/reconciler/contour/config/store.go
  pkg/reconciler/contour/config/store_test.go
  test/e2e-common.sh
  test/upload-test-images.sh
Labels: approved, lgtm, size/S

#1112 Add support for cluster local tls
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
Labels: approved, lgtm, size/L

#1115 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1116 Use a different 'static' image that supports s390x and ppc
  .ko.yaml
Labels: approved, lgtm, size/XS

#1119 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1120 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg/README.txt
  vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg/autoneg.go
  vendor/github.com/prometheus/procfs/.golangci.yml
  vendor/github.com/prometheus/procfs/MAINTAINERS.md
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/arp.go
  vendor/github.com/prometheus/procfs/buddyinfo.go
  vendor/github.com/prometheus/procfs/cpuinfo.go
  vendor/github.com/prometheus/procfs/crypto.go
  vendor/github.com/prometheus/procfs/fscache.go
  vendor/github.com/prometheus/procfs/ipvs.go
  vendor/github.com/prometheus/procfs/loadavg.go
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/meminfo.go
  vendor/github.com/prometheus/procfs/mountinfo.go
  vendor/github.com/prometheus/procfs/mountstats.go
  vendor/github.com/prometheus/procfs/net_conntrackstat.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/net_sockstat.go
  vendor/github.com/prometheus/procfs/net_softnet.go
  vendor/github.com/prometheus/procfs/net_tls_stat.go
  vendor/github.com/prometheus/procfs/net_unix.go
  vendor/github.com/prometheus/procfs/net_wireless.go
  vendor/github.com/prometheus/procfs/proc.go
  vendor/github.com/prometheus/procfs/proc_limits.go
  vendor/github.com/prometheus/procfs/proc_ns.go
  vendor/github.com/prometheus/procfs/proc_psi.go
  vendor/github.com/prometheus/procfs/proc_smaps.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/github.com/prometheus/procfs/proc_sys.go
  vendor/github.com/prometheus/procfs/softirqs.go
  vendor/github.com/prometheus/procfs/stat.go
  vendor/github.com/prometheus/procfs/swaps.go
  vendor/github.com/prometheus/procfs/thread.go
  vendor/github.com/prometheus/procfs/zoneinfo.go
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm
