Repository knative-extensions/net-contour, pull requests merged in 2024-02, with the labels that each got.

#1032 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1031 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_others.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_windows.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/networking/pkg/certificates/certs.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/key_pair.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1033 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1034 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1035 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1036 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1037 drop k8s 1.27 from kind testing
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/XS

#1038 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#1039 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1044 Bump cluster version to 1.28 in e2e scripts
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1045 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/informers/externalversions/factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1046 bump-go to v1.22
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/S

#1049 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/LICENSE
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1050 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_networking_client.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_realm.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/generated_expansion.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/networking_client.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/interface.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/networking/v1alpha1/realm.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/expansion_generated.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/realm.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm
