Repository knative-extensions/net-contour, pull requests merged in 2024-12, with the labels that each got.

#1148 Bump Kind and k8s version
  .github/workflows/kind-e2e.yaml
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1147 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1150 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1151 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
