Repository knative-extensions/net-contour, pull requests merged in 2025-04, with the labels that each got.

#1170 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1166 fix golangci-lint config
  .golangci.yaml
Labels: approved, lgtm, size/L

#1172 fix golangci config
  .golangci.yaml
Labels: approved, lgtm, size/M

#1168 [release-1.16] Upgrade to latest dependencies [skip-ci]
  go.mod
  go.sum
  test/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1174 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1176 Bump Contour to v1.30.3
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1177 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1178 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/endpointsharding/endpointsharding.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/transport/client_stream.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/server_stream.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL
