Repository knative-extensions/net-contour, pull requests merged in 2025-01, with the labels that each got.

#1152 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1149 bump contour to 1.30.1
  .golangci.yaml
  config/contour/external.yaml
  config/contour/internal.yaml
  go.mod
  go.sum
  hack/overlays/disable-envoy-daemonset-hostport.yaml
  hack/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1155 update linter settings to match knative/pkg
  .golangci.yaml
  pkg/reconciler/contour/config/contour.go
  pkg/reconciler/contour/config/contour_test.go
  pkg/reconciler/contour/contour.go
  pkg/reconciler/contour/contour_test.go
  pkg/reconciler/contour/resources/constants.go
  pkg/reconciler/contour/resources/httpproxy.go
  pkg/reconciler/contour/resources/httpproxy_test.go
  pkg/reconciler/testing/factory.go
  test/conformance/headless_rewrite_test.go
  test/conformance/ingress_test.go
Labels: size/XXL, approved, lgtm

#1157 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1158 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1159 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1160 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1161 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1163 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
